language: java
jdk:
  - openjdk8

branches:
  only:
    - master

cache:
  directories:
    - '$HOME/.m2'

before_install:
  - chmod +x mvnw

script: "./mvnw clean install -DskipTests"

before_deploy:
  - zip -r RemakeDiabetesDiaryAPI *
  - mkdir -p deploy
  - mv RemakeDiabetesDiaryAPI.zip deploy/RemakeDiabetesDiaryAPI.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: dasd412-sprinboot-build
    region: ap-northeast-2
    cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true



notifications:
  email:
    recipients:
      - dasd412@naver.com
