# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

# name for repository action page
name: RemakeDiabetesDiaryAPI & Maven CI

# master branch에 push 또는 PR 발생 시 동작하는 이벤트 트리거
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    # 실행 환경
    runs-on: ubuntu-latest
    
    # task의 순서 명시
    steps:
    - uses: actions/checkout@v2
    
    # ec2 instance 내 java 환경은 1.8 
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: '1.8'

    - name: Grant execute permission for mavenw
      run: chmod +x mvnw
      
    # 빌드하기 
    - name: Build with Maven 
      run: ./mvnw clean package
    
    # 전송할 파일을 담을 디렉토리 생성
    - name: Make directory for delivery
      run: mkdir -p before-deploy
    
    # jar file 복사하기
    - name: copy jar file
      run: cp target/*.jar before-deploy/
    
    # 압축파일 형태 만들기
    - name : make zip file
      run : cd before-deploy && zip -r before-deploy *
    
    # 이전 디렉토리 이동 및 새 디렉토리 생성
    - name : move previous and make new directory
      run : cd ../ && mkdir -p deploy
    
    # zip 파일 이동
    - name : move zip file
      run : mv before-deploy/before-deploy.zip deploy/RemakeDiabetesDiaryAPI.zip
    
    # s3 bucket으로 복사
    - name: deliver to AWS S3 bucket
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws s3 cp \
        --region ap-northeast-2 \
        --acl private \ 
        deploy/RemakeDiabetesDiaryAPI.zip s3://RemakeDiabetesDiaryAPI-deploy/
      

