name: release draft

# master branch에 push 발생 시
on:
  push:
    branches:
      - master

jobs:
  update_release_draft:
    # 실행 환경
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        with:
          config_name: release-draft-config.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

